# Generated by Django 5.0.3 on 2024-03-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
