# Generated by Django 5.0.4 on 2024-04-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="HereticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_num", models.IntegerField()),
                ("image", models.ImageField(upload_to="HPages/")),
            ],
        ),
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name_plural": "Images"},
        ),
    ]
