# Generated by Django 5.0.4 on 2024-04-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_hereticpage_alter_images_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="hereticpage",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
